application: app_name
version: 1
runtime: python27
api_version: 1
threadsafe: yes


handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /content
  static_dir: content

- url: /images
  static_dir: images

- url: /scripts
  static_dir: scripts

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"
